name: "Setup Environment"
description: "Checkout repository, setup uv, install asv, and configure git"
inputs:
  python-version:
    description: "Python version to install with uv"
    required: true
  additional-python-versions:
    description: "Additional Python versions to install with uv (space-separated)"
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        clean: false

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true
        prune-cache: false

    - name: Install additional Python versions for ASV
      if: inputs.additional-python-versions != ''
      run: uv python install ${{ inputs.additional-python-versions }}

    - name: Install  ASV
      run: uv pip install asv

    - name: Configure git
      run: |
        git config user.email "asv@ci"
        git config user.name "airspeed velocity"
