name: airspeed velocity

on:
  workflow_dispatch:


jobs:
  python-version-check:
    # concurrency:
    #   group: asv-benchmarking
    #   cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      matrix:
        os: [Windows, Linux]

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Update PATH (Linux)
        if: matrix.os == 'Linux'
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Update PATH (Windows)
        if: matrix.os == 'Windows'
        run: echo "$env:HOMEPATH/.local/bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Check and Install Python versions
        run: |
          uv python list
          uv python install 3.12
