name: airspeed velocity

on:
  workflow_dispatch:

jobs:
  benchmarking:
    concurrency:
      group: asv-benchmarking
      cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      matrix:
        include:
          - os: Linux
            MACHINE: BOSGAME-SUE4P-wsl

          - os: Windows
            MACHINE: BOSGAME-SUE4P-windows

    steps:
      - uses: ./.github/actions/setup-env
        with:
          python-version: "3.12"
          additional-python-versions: "3.11"

      - name: Run ASV
        run: |
          for tag in $(cd aequilibrae/ && git tag -l | tail -n 5); do asv --machine ${{ matrix.MACHINE }} run "$tag^!"; done

  results:
    needs: [benchmarking]
    runs-on: [self-hosted, Linux]
    steps:
      - uses: ./.github/actions/setup-env
        with:
          python-version: "3.12"

      - name: Publish to GitHub pages
        run: |
          cp -r /mnt/c/actions-runner/_work/benchmarks/benchmarks/results/BOSGAME-SUE4P-windows results/
          asv publish
          asv gh-pages

      - name: Upload results as artefact
        uses: actions/upload-artifact@v4
        with:
          name: asv-results
          path: ./results/
          overwrite: true
