name: Run airspeed velocity

on:
  workflow_dispatch:

jobs:
  benchmarking:
    concurrency:
      group: asv-benchmarking
      cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      matrix:
        include:
          - os: Linux
            MACHINE: BOSGAME-SUE4P-wsl

          - os: Windows
            MACHINE: BOSGAME-SUE4P-windows

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          prune-cache: false

      - name: Install additional Python versions for ASV
        run: uv python install 3.10 3.11 3.12 --preview

      - name: Install  ASV
        run: uv pip install asv

      - name: Run ASV (Linux)
        if: matrix.os == 'Linux'
        run: |
          for tag in $(cd aequilibrae/ && git tag -l | tail -n 5); do asv run "$tag^!" --machine ${{ matrix.MACHINE }} ; done

      - name: Run ASV (Windows)
        if: matrix.os == 'Windows'
        run: |
          $tags = git -C aequilibrae tag -l | Select-String -Pattern '.*' | Select-Object -Last 5
          foreach ($tag in $tags) {
              asv run "$($tag.ToString().Trim())^!" --machine ${{ matrix.MACHINE }}
          }
