name: airspeed velocity

on:
  workflow_dispatch:


jobs:
  python-version-check:
    # concurrency:
    #   group: asv-benchmarking
    #   cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os}}"]
    strategy:
      matrix:
        os: [Windows, Linux]

    steps:
      - name: Check and Install Python versions
        run: |
          uv python list
          uv python install 3.12
