name: airspeed velocity

on:
  workflow_dispatch:


jobs:
  benchmarking:
    concurrency:
      group: asv-benchmarking
      cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      matrix:
        include:
          - os: Linux
            MACHINE: BOSGAME-SUE4P-wsl

          - os: Windows
            MACHINE: BOSGAME-SUE4P-windows

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          prune-cache: false

      - name: Install ASV and python versions for ASV
        run: |
          uv python install 3.11 3.12
          uv pip install asv

      - name: Run ASV
        run: |
          asv machine --os ${{ matrix.os }} --cpu "AMD Ryzen 9 6900HX with Radeon Graphics" --machine ${{ matrix.MACHINE }} --num_cpu "16" --ram "32G"
          asv run --machine ${{ matrix.MACHINE }}


  results:
    needs: [benchmarking]
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          prune-cache: false

      - name: Install ASV and python versions for ASV
        run: |
          uv python install 3.11 3.12
          uv pip install asv

      - name: Publish to GitHub pages
        run: |
          git config user.email "asv@ci"
          git config --global user.name "airspeed velocity"
          cp -r /mnt/c/actions-runner/_work/benchmarks/benchmarks/results/BOSGAME-SUE4P-windows results/
          asv publish
          asv gh-pages

      - name: Upload results as artefact
        uses: actions/upload-artifact@v4
        with:
          name: asv-results
          path: ./results/
          overwrite: true
