name: airspeed velocity

on:
  workflow_dispatch:


jobs:
  python-version-check:
    # concurrency:
    #   group: asv-benchmarking
    #   cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      matrix:
        os: [Windows, Linux]

    steps:
      - name: Update PATH (Linux)
        if: matrix.os == 'Linux'
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Update PATH (Windows)
        if: matrix.os == 'Windows'
        run: |
          echo "C:\Users\admin\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Check and Install Python versions
        run: |
          uv python list
          uv python install 3.12
