name: airspeed velocity

on:
  workflow_dispatch:


jobs:
  benchmarking:
    concurrency:
      group: asv-benchmarking
      cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      matrix:
        include:
          - os: Windows
            MACHINE: BOSGAME-SUE4P-windows

          - os: Linux
            MACHINE: BOSGAME-SUE4P-wsl

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          prune-cache: false

      - name: Install ASV and python versions for ASV
        run: |
          uv python install 3.11 3.12
          uv pip install asv

      - name: Run ASV
        run: asv run --machine ${{ matrix.MACHINE }}
