name: Run airspeed velocity

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  benchmarking:
    concurrency:
      group: asv-benchmarking
      cancel-in-progress: false
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      matrix:
        include:
          - os: Linux
            MACHINE: BOSGAME-SUE4P-wsl

          - os: Windows
            MACHINE: BOSGAME-SUE4P-windows

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          prune-cache: false

      - name: Install additional Python versions for ASV
        run: uv python install 3.10 3.11 3.12 --preview --force

      - name: Install  ASV
        run: uv pip install asv

      - name: Run ASV
        run: asv run --machine ${{ matrix.MACHINE }} NEW
